#Name of the GitHub Action
name: Deploy Logic Apps

#Set the action on which the workflow will trigger
on:
 push:
  branches:
     - 'Dev'
 pull_request:
  branches: 
     - master
     - release*

jobs:
  
  DeployDev:
   name: Deploy to Dev
   runs-on: ubuntu-latest
   environment:
    name: Dev
   env:
     ENV_RESOURCEGROUP: devrg
     ENV_RESOURCEGROUPLOCATION: uksouth

   steps:
    #Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
       ref: 'Dev'
    

    #Use the azure provided action to log on to azure using service pricipal
    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
    
    #Validate the  ARM template
    - name: Validate ARM template
      run: |
        az deployment group validate -g ${{env.ENV_RESOURCEGROUP}} --mode Incremental --template-file ./get-student-api-la/LogicApp.json --parameters ./get-student-api-la/LogicApp.parameters.json
    
    #Deploy the ARM Template
    - name: Deploy Logic App
      run: |
        az deployment group create -g ${{env.ENV_RESOURCEGROUP}} --template-file ./get-student-api-la/LogicApp.json --parameters ./get-student-api-la/LogicApp.parameters.json
      shell: bash   
      
    # Log Out From Azure 
    - name: Logout
      run: az logout
   
  DeployTest:
   name: Deploy to Test
   if: github.event_name =='pull_request'
   runs-on: ubuntu-latest
   environment:
    name: Test
   env:
     ENV_RESOURCEGROUP: testrg
     ENV_RESOURCEGROUPLOCATION: uksouth

   steps:
    #Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
       ref: 'release*'
    

    #Use the azure provided action to log on to azure using service pricipal
    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
    
    #Validate the  ARM template
    - name: Validate ARM template
      run: |
        az deployment group validate -g ${{env.ENV_RESOURCEGROUP}} --mode Incremental --template-file ./get-student-api-la/LogicApp.json --parameters ./get-student-api-la/LogicApp.parameters.json
    
    #Deploy the ARM Template
    - name: Deploy Logic App
      run: |
        az deployment group create -g ${{env.ENV_RESOURCEGROUP}} --template-file ./get-student-api-la/LogicApp.json --parameters ./get-student-api-la/LogicApp.parameters.json
      shell: bash   
      
    # Log Out From Azure 
    - name: Logout
      run: az logout    
