#Name of the GitHub Action
name: Deploy Logic App

#Set the action on which the workflow will trigger
on:
 push:
   branches:
     - master

jobs:
  validate-and-deploy:
   runs-on: ubuntu-latest
   env:
     ENV_RESOURCEGROUP: testrg
     ENV_RESOURCEGROUPLOCATION: uksouth

   steps:

    #Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@master

    #Use the azure provided action to log on to azure using service pricipal
    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
    
    #Validate the  ARM template
    - name: Validate ARM template
      run: |
        az deployment group validate -g ${{env.ENV_RESOURCEGROUP}} --mode Incremental --template-file ./get-student-api-la/LogicApp.json --parameters ./get-student-api-la/LogicApp.parameters.json
    
    #Deploy the ARM Template
    - name: Deploy Logic App
      run: |
        az deployment group validate -g ${{env.ENV_RESOURCEGROUP}} --template-file ./get-student-api-la/LogicApp.json --parameters ./get-student-api-la/LogicApp.parameters.json
      shell: bash   
      
    # Log Out From Azure 
    - name: Logout
      run: az logout
 
